name: mecanum_wheel_drivetrain_controller
description: Mobile app interface to control a mecanum wheel drivetrain

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  mqtt_client: ^9.7.2
  sensors_plus: ^0.0.1
  flutter_sensors: ^1.0.1
  flutter_dotenv: ^5.0.2
  flutter_bluetooth_serial: ^0.4.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  flutter_blue: ^0.8.0
  permission_handler: ^10.2.0
  font_awesome_flutter: ^10.3.0
  rive: ^0.9.1
  bloc: ^8.1.0
  app_settings: ^4.1.8

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  freezed: ^2.3.1
  json_serializable: ^6.5.4
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
